ALTER TABLE item_seed ADD COLUMN IF NOT EXISTS image_url VARCHAR(500);

ALTER TABLE item_seed DROP CONSTRAINT IF EXISTS item_seed_category_name_key;
ALTER TABLE item_seed ADD CONSTRAINT item_seed_category_name_image_url_key UNIQUE (category, name, image_url);

INSERT INTO item_seed (category, name, image_url, sort_order) VALUES
    ('WEAPON_CAST', 'Focus', '/forces/focus.png', 1),
    ('WEAPON_CAST', 'Energize', '/forces/energize.png', 2),
    ('WEAPON_CAST', 'Soul Vitality', '/forces/soul-vitality.png', 3),
    ('WEAPON_CAST', 'Resistance', '/forces/resistance.png', 4),
    ('WEAPON_CAST', 'Healing', '/forces/healing.png', 5),
    ('WEAPON_CAST', 'Velocity', '/forces/velocity.png', 6),
    ('WEAPON_CAST', 'Agility', '/forces/agility.png', 7),
    ('WEAPON_CAST', 'Aegis', '/forces/aegis.png', 8),
    ('WEAPON_CAST', 'Conservation', '/forces/conservation.png', 9),
    ('WEAPON_CAST', 'Prism Shard', '/forces/prism-shard.png', 10),
    ('WEAPON_CAST', 'Fire Wall', '/forces/fire-wall.png', 11),
    ('WEAPON_CAST', 'Fire Ball', '/forces/fire-ball.png', 12),
    ('WEAPON_CAST', 'Flash Beam', '/forces/flash-beam.png', 13),
    ('WEAPON_CAST', 'Flame Arrow', '/forces/flame-arrow.png', 14),
    ('WEAPON_CAST', 'Circle of Fire', '/forces/circle-of-fire.png', 15),
    ('WEAPON_CAST', 'Fire Bomb', '/forces/fire-bomb.png', 16),
    ('WEAPON_CAST', 'Radiant Fall', '/forces/radiant-fall.png', 17),
    ('WEAPON_CAST', 'Blaze Pearl', '/forces/blaze-pearl.png', 18),
    ('WEAPON_CAST', 'Solar Blade', '/forces/solar-blade.png', 19),
    ('WEAPON_CAST', 'Blaze Lance', '/forces/blaze-lance.png', 20),
    ('WEAPON_CAST', 'Meteor Swarm', '/forces/meteor-swarm.png', 21),
    ('WEAPON_CAST', 'Ice Shard', '/forces/ice-shard.png', 22),
    ('WEAPON_CAST', 'Geyser', '/forces/geyser.png', 23),
    ('WEAPON_CAST', 'Blind Sight', '/forces/blind-sight.png', 24),
    ('WEAPON_CAST', 'Weakness', '/forces/weakness.png', 25),
    ('WEAPON_CAST', 'Frost Arrow', '/forces/frost-arrow.png', 26),
    ('WEAPON_CAST', 'Aqua Blade', '/forces/aqua-blade.png', 27),
    ('WEAPON_CAST', 'Vulnerability', '/forces/vulnerability.png', 28),
    ('WEAPON_CAST', 'Enfeeblement', '/forces/enfeeblement.png', 29),
    ('WEAPON_CAST', 'Raging Wave', '/forces/raging-wave.png', 30),
    ('WEAPON_CAST', 'Frost Nova', '/forces/frost-nova.png', 31),
    ('WEAPON_CAST', 'Sloth', '/forces/sloth.png', 32),
    ('WEAPON_CAST', 'Slow', '/forces/slow.png', 33),
    ('WEAPON_CAST', 'Vein Fall', '/forces/vein-fall.png', 34),
    ('WEAPON_CAST', 'Poison Mist', '/forces/poison-mist.png', 35),
    ('WEAPON_CAST', 'Suppress', '/forces/suppress.png', 36),
    ('WEAPON_CAST', 'Repress', '/forces/repress.png', 37),
    ('WEAPON_CAST', 'Rock Blade', '/forces/rock-blade.png', 38),
    ('WEAPON_CAST', 'Poison Bloom', '/forces/poison-bloom.png', 39),
    ('WEAPON_CAST', 'Stifle', '/forces/stifle.png', 40),
    ('WEAPON_CAST', 'Entangle', '/forces/entangle.png', 41),
    ('WEAPON_CAST', 'Venom', '/forces/venom.png', 42),
    ('WEAPON_CAST', 'Sand Storm', '/forces/sand-storm.png', 43),
    ('WEAPON_CAST', 'Restrain', '/forces/restrain.png', 44),
    ('WEAPON_CAST', 'Contain', '/forces/contain.png', 45),
    ('WEAPON_CAST', 'Spark', '/forces/spark.png', 46),
    ('WEAPON_CAST', 'Wind Shear', '/forces/wind-shear.png', 47),
    ('WEAPON_CAST', 'Counter', '/forces/counter.png', 48),
    ('WEAPON_CAST', 'Dispel', '/forces/dispel.png', 49),
    ('WEAPON_CAST', 'Lightning Bolt', '/forces/lightning-bolt.png', 50),
    ('WEAPON_CAST', 'Air Blast', '/forces/air-blast.png', 51),
    ('WEAPON_CAST', 'Refresh', '/forces/refresh.png', 52),
    ('WEAPON_CAST', 'Sight', '/forces/sight.png', 53),
    ('WEAPON_CAST', 'Wind Blast', '/forces/wind-blast.png', 54),
    ('WEAPON_CAST', 'Chain Lightning', '/forces/chain-lightning.png', 55),
    ('WEAPON_CAST', 'Individual Cancellation / Skill Revoker', '/forces/individual-cancellation-skill-revoker.png', 56),
    ('WEAPON_CAST', 'Offensive Cancellation / Force Revoker', '/forces/offensive-cancellation-force-revoker.png', 57),
    ('WEAPON_CAST', 'Celerity', '/forces/celerity.png', 58),
    ('WEAPON_CAST', 'Sacrifice', '/forces/sacrifice.png', 59),
    ('WEAPON_CAST', 'Tempo', '/forces/tempo.png', 60),
    ('WEAPON_CAST', 'Adept', '/forces/adept.png', 61),
    ('WEAPON_CAST', 'Vista', '/forces/vista.png', 62),
    ('WEAPON_CAST', 'Velocity / Speed', '/forces/velocity-speed.png', 63),
    ('WEAPON_CAST', 'Acute', '/forces/acute.png', 64),
    ('WEAPON_CAST', 'Torment', '/forces/torment.png', 65),
    ('WEAPON_CAST', 'Conservation', '/forces/conservation-dark.png', 66);
