package com.guild.app.common.enums;

public enum AuditLogType {
    OBJECTIVE_CREATED,
    OBJECTIVE_UPDATED,
    OBJECTIVE_DELETED,
    EVENT_CREATED,
    EVENT_CLAIMED,
    EVENT_DENIED,
    EVENT_CANCELLED,
    POINTS_ADJUSTED,
    AUCTION_CREATED,
    AUCTION_CLOSED,
    PROFILE_UPDATED,
    MEMBER_APPROVED,
    MEMBER_REJECTED,
    MEMBER_REGISTERED,
    MEMBER_ROLE_CHANGED
}
